app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Route::get('pdf', 'ControladorPdf@invoice');

Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', [
        'uses'  => 'HomeController@index',
        'as'    => 'home'
    ]);

    Route::group(['middleware' =>  'admins'], function (){

        Route::get('/buscar', [
            'uses' => 'HomeController@resulBusqueda',
            'as' => 'buscar',
        ]);

        Route::post('/buscar', [
            'uses' => 'HomeController@resulBusqueda',
            'as' => 'buscar',
        ]);

        Route::resource('users', 'ControladorUsers');

        Route::get('/eliminarcontr/{contratante}', [
            'uses' => 'ControladorContratantes@destroy',
            'as' => 'contratantes.eliminar',
        ]);

        Route::get('/eliminartrab/{trabajador}', [
            'uses' => 'ControladorTrabajadores@destroy',
            'as' => 'trabajadores.eliminar',
        ]);

        Route::get('/trabajadores/{trabajador}/edit', [
            'uses' => 'ControladorTrabajadores@edit',
            'as' => 'trabajadores.edit',
        ]);

        Route::get('/contratantes/{contratante}/edit', [
            'uses' => 'ControladorContratantes@edit',
            'as' => 'contratantes.edit',
        ]);

        Route::get('/eliminaruser/{usuario}', [ 
            'uses' => 'ControladorUsers@destroy',
            'as' => 'users.destroy',
        ]);
    });

    Route::group(['middleware' => 'gestor'], function (){

        Route::resource('contratantes', 'ControladorContratantes');

        Route::resource('trabajadores', 'ControladorTrabajadores');

    });

    Route::get('/ver_usuario/{usuario}', [
        'uses' => 'ControladorUsers@show',
        'as' => 'users.show',
    ]);

    Route::get('/pdfcontratante/{contratante}', [
        'uses'  => 'ControladorPdf@pdfContratante',
        'as'    => 'contratantes.pdf'
    ]);

    Route::get('/pdftrabajador/{trabajador}', [
        'uses'  => 'ControladorPdf@pdfTrabajador',
        'as'    => 'trabajadores.pdf'
    ]);
    
});

Route::get('/', [
    'uses'  => 'Auth\AuthController@getLogin',
    'as'    => 'auth.login'
]);
Route::post('/', [
    'uses'  => 'Auth\AuthController@postLogin',
    'as'    => 'auth.login'
]);
Route::get('/logout', [
    'uses'  => 'Auth\AuthController@getLogout',
    'as'    => 'auth.logout'
]);

Route::get('/recupcontraseña', [
    'uses'  => 'ControladorClave@recuperarform',
    'as'    => 'claves.restore'
]);

Route::post('/recupcontraseña', [
    'uses'  => 'ControladorClave@verificar',
    'as'    => 'claves.verificar'
]);

Route::put('/actcontraseña/{usuario}', [
    'uses'  => 'ControladorClave@actualizar',
    'as'    => 'claves.actualizar'
]);

resources/views/crearcontratante.blade.php
@extends('plantillas.default.default')

@section('titulo', 'Crear empleador')

@section('contenido')
	<div class="col-sm-offset-2 col-sm-8">
		<img src="{{ asset('img/logo.png') }}" class="pull-left">
		<br>
		@if(Auth::user()->tipo == 'administrador')
			<div class="pull-right text-center">
				{!! Form::open(['route' => 'buscar', 'method' => 'POST', 'target' => '_blank']) !!}
		            <p>BUSQUEDA ID</p>
		            <input type="text" name="busqueda">
		        {!! Form::close() !!}
			</div>
		@endif
		<div class="col-sm-12">
			{!! Form::open(['route' => 'contratantes.store', 'method' => 'POST', 'files' => true]) !!}
				<h2 class="text-center">Empleador</h2>
				<div class="form-group pull-right">
					<label>Fecha</label>
					<input name="fecha" type="date" value="{{ date('Y-m-d') }}" readonly required>
				</div>
				<div class="form-group col-sm-12">
					<label>Nombres y Apellidos</label>
					<input type="text" name="nombres" required class="form-control" placeholder="Ingrese sus nombres y apellidos">
				</div>
				<div class="form-group col-sm-6">
					<label>Direccion</label>
					<input type="text" name="direccion" required class="form-control" placeholder="Ingerse su direccion">
				</div>
				<div class="form-group col-sm-6">
					<label>Ciudad</label>
					{!! Form::select('ciudad', $ciudades, null, ['class' => 'form-control', 'placeholder' => 'Seleccione su ciudad', 'required']) !!}
				</div>
				<div class="form-group col-sm-6">
					<label>Barrio</label>
					<input type="text" name="barrio" required class="form-control" placeholder="Ingerse su barrio">
				</div>
				<div class="form-group col-sm-6">
					<label>Documento de Identidad</label>
					<input type="text" name="documento" required class="form-control" placeholder="Ingerse su documento de identificacion">
				</div>
				<div class="form-group col-sm-6">
					<label>Telefono</label>
					<input type="text" name="telefono" class="form-control" placeholder="Ingrese su numero telefonico">
				</div>
				<div class="form-group col-sm-6">
					<label>Celular</label>
					<input type="text" name="celular" class="form-control" placeholder="Ingrese su numero de movil">
				</div>
				<div class="form-group col-sm-6">
					<label>Tipo de predio</label>
					<input type="text" name="tpredio" required class="form-control" size="15" placeholder="Ingrese su predio">
				</div>
				<div class="form-group col-sm-3">
					<label>Personas a atender</label>
					<input type="text" name="personas" required class="form-control" placeholder="Ingrese cantidad de personas a atender">
				</div>
				<div class="form-group col-sm-3">
					<label>Adultos</label>
					<input type="text" name="adultos" required class="form-control" placeholder="Ingrese cantidad de adultos">
				</div>
				<div class="form-group col-sm-5">
					<label>Pisos</label>
					<input type="text" name="pisos" required class="form-control" placeholder="Ingrese cantidad de pisos">
				</div>
				<div class="form-group col-sm-3">
					<label>Mascotas</label>
					<input type="text" name="mascotas" required class="form-control" placeholder="Ingrese cantidad de mascotas">
				</div>
				<div class="form-group col-sm-2">
					<label>Tercera Edad</label>
					<input type="text" name="tedad" required class="form-control" placeholder="Ingrese cantidad de personas de tercera edad">
				</div>
				<div class="form-group col-sm-2">
					<label>Niños</label>
					<input type="text" name="ninos" required class="form-control" placeholder="Ingrese cantidad de niños">
				</div>
				<div class="form-group col-sm-6">
					<label>Salario</label>
					<input type="text" name="salario" required class="form-control" placeholder="Ingrese salario">
				</div>
				<div class="form-group col-sm-6">
					<label>Dias de descanso</label>
					<input type="text" name="ddescanso" required class="form-control" placeholder="Ingrese dias de descanso">
				</div>
				<div class="form-group col-sm-12 text-center">
					<label>
						Interna <input type="radio" name="ttrabajo" value="Interna">
					</label>
					<label>
						Externa <input type="radio" name="ttrabajo" value="Externa">
					</label>
					<label>
						Por dias <input type="radio" name="ttrabajo" value="Por dias">
					</label>
				</div>
				<div class="form-group col-sm-12">
					<label>Gestion</label>
					<textarea class="form-control" name="gestion" required placeholder="Ingrese su gestion"></textarea>
				</div>
				<div class="form-group col-sm-12">
					<h4 class="text-center titulosilver">Record</h4>
					<textarea class="form-control" name="historial" rows="15" required readonly disabled></textarea>
				</div>
				<div class="form-group col-sm-6">
					<label>Subir Imagen</label>
					<input type="file" name="imagen">
					<p class="text-justify">La imagen debe poseer las siguientes dimensiones: 150px de Ancho por 150px de Alto</p>
				</div>
				<div class="form-group col-sm-6 text-right">
					<a href="{{ route('home') }}" class="btn btn-personal">Inicio</a>
					<input type="submit" name="registrar" value="Guardar" class="btn btn-personal">
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/crearhojavida.blade.php
@extends('plantillas.default.default')

@section('titulo', 'Nueva hoja de vida')

@section('contenido')
	<div class="col-sm-offset-2 col-sm-8">
		<img src="{{ asset('img/logo.png') }}" class="pull-left">
		<br>
		@if(Auth::user()->tipo == 'administrador')
			<div class="pull-right text-center">
				{!! Form::open(['route' => 'buscar', 'method' => 'GET', 'target' => '_blank']) !!}
		            <p>BUSQUEDA ID</p>
		            <input type="text" name="busqueda">
		        {!! Form::close() !!}
			</div>
		@endif
		<div class="col-sm-12">
			{!! Form::open(['route' => 'trabajadores.store', 'method' => 'POST', 'files' => true]) !!}
				<h2 class="text-center">Curriculum de Trabajo</h2>
				<div class="form-group pull-right">
					<label>Fecha</label>
					<input name="fecha" type="date" value="{{ date('Y-m-d') }}" readonly required>
				</div>
				<div class="form-group col-sm-12">
					<label>Nombres y Apellidos</label>
					<input type="text" name="nombres" required class="form-control" placeholder="Ingresa tu nombre y apellido">
				</div>
				<div class="form-group col-sm-6">
					<label>Direccion</label>
					<input type="text" name="direccion" required class="form-control" placeholder="Ingresa tu direccion">
				</div>
				<div class="form-group col-sm-6">
					<label>Ciudad</label>
					{!! Form::select('ciudad', $ciudades, null, ['class' => 'form-control', 'placeholder' => 'Seleccione su ciudad', 'required']) !!}
				</div>
				<div class="form-group col-sm-6">
					<label>Barrio</label>
					<input type="text" name="barrio" required class="form-control" placeholder="Ingresa tu barrio">
				</div>
				<div class="form-group col-sm-6">
					<label>Documento de Identidad</label>
					<input type="text" name="documento" required class="form-control" placeholder="Ingresa tu documento de identidad">
				</div>
				<div class="form-group col-sm-6">
					<label>Telefono</label>
					<input type="text" name="telefono" required class="form-control" placeholder="Ingresa tu numero telefonico">
				</div>
				<div class="form-group col-sm-6">
					<label>Celular</label>
					<input type="text" name="celular" required class="form-control" placeholder="Ingresa el numero de tu movil">
				</div>
				<div class="form-group col-sm-6">
					<label>Fecha de nacimiento AAAA/MM/DD</label>
					<input type="date" name="fechnac" required class="form-control" size="15" placeholder="Año - Mes - Dia">
				</div>
				<div class="form-group col-sm-6">
					<label>Lugar de nacimiento</label>
					<input type="text" name="lugar" required class="form-control" size="15" placeholder="Ingresa tu lugar de nacimeinto">
				</div>
				<div class="form-group col-sm-12">
					<label>Gestion</label>
					<textarea class="form-control" name="gestion" required placeholder="Ingresa tu gestion"></textarea>
				</div>
				<div class="form-group col-sm-12">
					<h4 class="text-center titulosilver">Record</h4>
					<textarea class="form-control" name="historial" rows="15" required readonly disabled></textarea>
				</div>
				<div class="form-group col-sm-6">
					<label>Subir Imagen</label>
					<input type="file" name="imagenes[]" multiple>
					<input type="file" name="imagenes[]" multiple>
					<input type="file" name="imagenes[]" multiple>
					<input type="file" name="imagenes[]" multiple>
					<input type="file" name="imagenes[]" multiple>
					<p class="text-justify">Las imagenes deben poseer las siguientes dimensiones: 150px de Ancho por 150px de Alto</p>
				</div>
				<div class="form-group col-sm-6 text-right">
					<a href="{{ route('home') }}" class="btn btn-personal">Inicio</a>
					<input type="submit" name="registrar" value="Guardar" class="btn btn-personal">
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/crearusuarios.blade.php
@extends('plantillas.default.default')

@section('css')
	<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/css/jquery.datatables.css') }}">
@endsection

@section('contenido')
	<div class="col-sm-offset-1 col-sm-10">
		<h2 class="text-center">Gestor de Usuarios</h2>
		<table id="listusuarios" class="table table-hover text-center">
			<thead>
				<tr>
					<th>Usuario</th>
					<th>Fecha</th>
					<th>Estatus</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
				@foreach($usuarios as $usuario)
					<tr>
						<td>{{ $usuario->user }}</td>
						<td>{{ $usuario->created_at->toDateString() }}</td>
						<td>{{ $usuario->tipo }}</td>
						<td>
							<a href="#" class="btn btn-personal" data-toggle="modal" data-target="#{{$usuario->user}}">Editar</a>
							<a href="{{ route('users.destroy', $usuario) }}" class="btn btn-personal" onclick="return confirm('¿Desea eliminar este Usuario?')">Eliminar</a>
						</td>
					</tr>
				@endforeach
			</tbody>
		</table>
		<p class="text-justify">
			<a href="{{ route('home') }}" class="btn btn-personal">Inicio</a>
			<a href="#" class="btn btn-personal" data-toggle="modal" data-target="#regusuario">Nuevo</a>
		</p>
	</div>
	@foreach($usuarios as $usuario)
		<div class="modal fade" id="{{$usuario->user}}" tabindex="-1" role="dialog" aria-labelledby="{{$usuario->user}}">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
						<h4 class="modal-title" id="{{$usuario->user}}">Editar Usuario: {{ $usuario->user }}</h4>
					</div>
					<div class="modal-body">
						{!! Form::open(['route' => ['users.update', $usuario], 'method' => 'PUT']) !!}
							<div class="form-group">
								{!! Form::label('usuario', 'Usuario') !!}
								{!! Form::text('usuario', $usuario->user, ['class' => 'form-control']) !!}
							</div>
							<div class="form-group">
								{!! Form::label('tusuario', 'Estatus') !!}
								{!! Form::select('tusuario', ['administrador' => 'Administrador', 'gestor' => 'Gestor'], $usuario->tipo, ['class' => 'form-control']) !!}
							</div>
							<div class="form-group">
								{!! Form::label('correo', 'Email') !!}
								{!! Form::email('correo', $usuario->correo, ['class' => 'form-control']) !!}
							</div>
							<div class="form-group">
								{!! Form::label('clave', 'Nueva Contraseña') !!}
								{!! Form::password('clave', ['class' => 'form-control']) !!}
							</div>
							<div class="form-group">
								{!! Form::label('clave2', 'Repetir Contraseña') !!}
								{!! Form::password('clave2', ['class' => 'form-control']) !!}
							</div>
							<div class="form-group">
								<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
								<button type="submit" class="btn btn-primary">Guardar</button>
							</div>
						{!! Form::close() !!}
					</div>
				</div>	
			</div>
		</div>
	@endforeach
	<div class="modal fade" id="regusuario" tabindex="-1" role="dialog" aria-labelledby="regusuario">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h4 class="modal-title" id="regusuario">Registrar nuevo usuario</h4>
				</div>
				<div class="modal-body">
					{!! Form::open(['route' => 'users.store', 'method' => 'POST']) !!}
						<div class="form-group">
							{!! Form::label('usuario', 'Usuario') !!}
							{!! Form::text('usuario', null, ['class' => 'form-control', 'placeholder' => 'Ingerese el usuario', 'required']) !!}
						</div>
						<div class="form-group">
							{!! Form::label('tusuario', 'Estatus') !!}
							{!! Form::select('tusuario', ['administrador' => 'Administrador', 'gestor' => 'Gestor'], null, ['class' => 'form-control', 'placeholder' => 'Seleccione una opcion', 'required']) !!}
						</div>
						<div class="form-group">
							{!! Form::label('correo', 'Email') !!}
							{!! Form::email('correo', null, ['class' => 'form-control', 'placeholder' => 'Ingrese el E-mail', 'required']) !!}
						</div>
						<div class="form-group">
							{!! Form::label('clave', 'Clave') !!}
							{!! Form::password('clave', ['class' => 'form-control', 'placeholder' => 'Ingrese la contraseña' ,'required']) !!}
						</div>
						<div class="form-group">
							{!! Form::label('rep_clave', 'Repetir Clave') !!}
							{!! Form::password('rep_clave', ['class' => 'form-control', 'placeholder' => 'Repita la contraseña' , 'required']) !!}
						</div>
						<div class="form-group">
							<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
							<button type="submit" class="btn btn-primary">Guardar</button>
						</div>
					{!! Form::close() !!}
				</div>
			</div>	
		</div>
	</div>
@endsection

@section('scripts')
	<script src="{{ asset('plugins/datatables/js/jquery.dataTables.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function() {
		    $('#listusuarios').DataTable({
		    	"language": {
		            "lengthMenu": "Ver _MENU_ entradas por pagina",
		            "zeroRecords": "No se encontraron resultados",
		            "info": "Viendo la pagina _PAGE_ de _PAGES_",
		            "infoEmpty": "No hay informacion",
		            "search": "Buscar: ",
		            "paginate": {
				        "previous": "Anterior ",
				        "next": " Proximo",
				    }
		        }
		    });
		} );
	</script>
@endsection

resources/views/home.blade.php
@extends('plantillas.default.default')

@section('contenido')
    <div class="col-sm-offset-4 col-sm-4">
        <img src="{{ asset('img/logo.png') }}" class="center-block">
        <div class="text-center">
            @if(Auth::user()->tipo == 'administrador' || Auth::user()->tipo == 'gestor')
                <a href="{{ route('trabajadores.create') }}" class="btn btn-personal" target="_blank">Nueva Hoja de Vida</a>
                <a href="{{ route('contratantes.create') }}" class="btn btn-personal" target="_blank">Nuevo Empleador</a>
            @endif
        </div>
    </div>
    <br>
    <br>
    <div class="col-sm-1">
        <a href="{{ route('auth.logout') }}" class="btn btn-personal">
            Cerrar Sesion
        </a>
    </div>
    @if(Auth::user()->tipo == 'administrador')
        <div class="col-sm-offset-1 col-sm-8 text-center">
            {!! Form::open(['route' => 'buscar', 'method' => 'POST', 'class' => 'col-sm-3', 'target' => '_blank']) !!}
                <p>BUSQUEDA ID</p>
                <input type="text" name="busqueda">
            {!! Form::close() !!}
            <br>
            <a href="{{ route('trabajadores.index') }}" class="btn btn-personal" target="_blank">Listado de Empleados</a>
            <a href="{{ route('contratantes.index') }}" class="btn btn-personal" target="_blank">Listado de Empleadores</a>
            <a href="{{ route('users.create') }}" class="btn btn-personal" target="_blank">Gestor de Usuarios</a>
        </div>
    @endif
@endsection

resources/views/listcontratante.blade.php
@extends('plantillas.default.default')

@section('css')
	<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/css/jquery.datatables.css') }}">
@endsection

@section('contenido')
	<div class="col-sm-offset-1 col-sm-10 text-justify">
		<h2 class="text-center">Listado de Empleadores</h2>
		<table id="liscontratantes" class="table table-hover">
			<thead>
				<tr>
					<th>Nombre y Apellido</th>
					<th>Personas a Atender</th>
					<th>Predio</th>
					<th>Pisos</th>
					<th>Salario</th>
					<th>Modo de Trabajo</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
				@foreach($contratantes as $contratante)
					<tr>
						<td>{{ $contratante->nombres }}</td>
						<td>{{ $contratante->pers_atend }}</td>
						<td>{{ $contratante->predio->predio }}</td>
						<td>{{ $contratante->pisos }}</td>
						<td>{{ $contratante->Salario }}</td>
						<td>{{ $contratante->ttrabajo }}</td>
						<td><a href="{{ route('contratantes.show', $contratante) }}" class="btn btn-personal" target="_blank">Ver</a></td>
					</tr>
				@endforeach
			</tbody>
		</table>
		<p class="text-justify">
			<a href="{{ route('home') }}" class="btn btn-personal">Inicio</a>
		</p>
	</div>
@endsection

@section('scripts')
	<script src="{{ asset('plugins/datatables/js/jquery.dataTables.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function() {
		    $('#liscontratantes').DataTable({
		    	"language": {
		            "lengthMenu": "Ver _MENU_ entradas por pagina",
		            "zeroRecords": "No se encontraron resultados",
		            "info": "Viendo la pagina _PAGE_ de _PAGES_",
		            "infoEmpty": "No hay informacion",
		            "search": "Buscar: ",
		            "paginate": {
				        "previous": "Anterior ",
				        "next": " Proximo",
				    }
		        }
		    });
		} );
	</script>
@endsection

resources/views/listtrabajador.blade.php
@extends('plantillas.default.default')

@section('css')
	<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/css/jquery.datatables.css') }}">
@endsection

@section('contenido')
	<div class="col-sm-offset-1 col-sm-10 text-justify">
		<h2 class="text-center">Listado de Empleados</h2>
		<table id="listrabajadores" class="table table-hover">
			<thead>
				<tr>
					<th>Nombre y Apellido</th>
					<th>Edad (años)</th>
					<th>Ciudad</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
				@foreach($trabajadores as $trabajador)
					<tr>
						<td>{{ $trabajador->nombres }}</td>
						<td>{{ $trabajador->edad($trabajador->fech_naci) }}</td>
						<td>{{ $trabajador->ciudad->ciudad }}</td>
						<td><a href="{{ route('trabajadores.show', $trabajador) }}" class="btn btn-personal" target="_blank">Ver</a></td>
					</tr>
				@endforeach
			</tbody>
		</table>

		<p class="text-justify">
			<a href="{{ route('home') }}" class="btn btn-personal">Inicio</a>
		</p>
	</div>
@endsection

@section('scripts')
	<script src="{{ asset('plugins/datatables/js/jquery.dataTables.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function() {
		    $('#listrabajadores').DataTable({
		    	"language": {
		            "lengthMenu": "Ver _MENU_ entradas por pagina",
		            "zeroRecords": "No se encontraron resultados",
		            "info": "Viendo la pagina _PAGE_ de _PAGES_",
		            "infoEmpty": "No hay informacion",
		            "search": "Buscar: ",
		            "paginate": {
				        "previous": "Anterior ",
				        "next": " Proximo",
				    }
		        }
		    });
		} );
	</script>
@endsection

resources/views/resulbuscar.blade.php
@extends('plantillas.default.default')

@section('titulo', 'Resultado de la Busqueda')

@section('css')
	<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/css/jquery.datatables.css') }}">
@endsection

@section('contenido')

	<h2 class="text-center">Resultado de la busqueda</h2>
	<div class="col-sm-offset-1 col-sm-10">
		<div class="pull-right">
			<p class="text-center">
				BUSQUEDA ID
			</p>
			{!! Form::open(['route' => 'buscar', 'method' => 'POST', 'class' => 'col-sm-3']) !!}
				<input type="text" name="busqueda">
			{!! Form::close() !!}
		</div>
		<div class="col-sm-12">
			<h3 class="text-center">Trabajadores</h3>
			<hr>
			<table id="listrabajadores" class="table table-hover">
				<thead>
					<tr>
						<th>Nombre y Apellido</th>
						<th>Edad (años)</th>
						<th>Ciudad</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					@foreach($trabajadores as $trabajador)
						<tr>
							<td>{{ $trabajador->nombres }}</td>
							<td>{{ $trabajador->edad($trabajador->fech_naci) }}</td>
							<td>{{ $trabajador->ciudad->ciudad }}</td>
							<td><a href="{{ route('trabajadores.show', $trabajador) }}" class="btn btn-personal" target="_blank">Ver</a></td>
						</tr>
					@endforeach
				</tbody>
			</table>
			<h3 class="text-center">Contratantes</h3>
			<hr>
			<table id="liscontratantes" class="table table-hover">
				<thead>
					<tr>
						<th>Nombre y Apellido</th>
						<th>Personas a Atender</th>
						<th>Predio</th>
						<th>Pisos</th>
						<th>Salario</th>
						<th>Modo de Trabajo</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					@foreach($contratantes as $contratante)
						<tr>
							<td>{{ $contratante->nombres }}</td>
							<td>{{ $contratante->pers_atend }}</td>
							<td>{{ $contratante->predio->predio }}</td>
							<td>{{ $contratante->pisos }}</td>
							<td>{{ $contratante->Salario }}</td>
							<td>{{ $contratante->ttrabajo }}</td>
							<td><a href="{{ route('contratantes.show', $contratante) }}" class="btn btn-personal" target="_blank">Ver</a></td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>
		<p class="text-justify col-sm-12">
			<a href="{{ route('home') }}" class="btn btn-personal">Inicio</a>
		</p>
	</div>
@endsection

@section('scripts')
	<script src="{{ asset('plugins/datatables/js/jquery.dataTables.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function() {
		    $('#listrabajadores').DataTable({
		    	"language": {
		            "lengthMenu": "Ver _MENU_ entradas por pagina",
		            "zeroRecords": "No se encontraron resultados",
		            "info": "Viendo la pagina _PAGE_ de _PAGES_",
		            "infoEmpty": "No hay informacion",
		            "search": "Buscar: ",
		            "paginate": {
				        "previous": "Anterior ",
				        "next": " Proximo",
				    }
		        }
		    });
		    $('#liscontratantes').DataTable({
		    	"language": {
		            "lengthMenu": "Ver _MENU_ entradas por pagina",
		            "zeroRecords": "No se encontraron resultados",
		            "info": "Viendo la pagina _PAGE_ de _PAGES_",
		            "infoEmpty": "No hay informacion",
		            "search": "Buscar: ",
		            "paginate": {
				        "previous": "Anterior ",
				        "next": " Proximo",
				    }
		        }
		    });
		} );
	</script>
@endsection